@echo off
REM ============================================================================
REM Interactive Setup Script for Minimal Agent (Windows)
REM ============================================================================
REM
REM This script guides users through the setup process by:
REM 1. Checking for required dependencies (Docker, Git)
REM 2. Prompting for configuration values
REM 3. Creating .env file with user-provided values
REM 4. Building the Docker image
REM 5. Verifying the setup
REM
REM Usage: setup.bat
REM ============================================================================

setlocal enabledelayedexpansion

echo ============================================================================
echo Minimal Agent Setup (Windows)
echo ============================================================================
echo.

REM ----------------------------------------------------------------------------
REM Step 1: Check Dependencies
REM ----------------------------------------------------------------------------
echo [1/5] Checking dependencies...
echo.

REM Check Docker
docker --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker is not installed or not in PATH.
    echo.
    echo Please install Docker Desktop from:
    echo https://www.docker.com/products/docker-desktop
    echo.
    pause
    exit /b 1
)
echo [OK] Docker is installed

REM Check Git
git --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Git is not installed or not in PATH.
    echo.
    echo Please install Git from:
    echo https://git-scm.com/download/win
    echo.
    pause
    exit /b 1
)
echo [OK] Git is installed
echo.

REM ----------------------------------------------------------------------------
REM Step 2: Gather Configuration
REM ----------------------------------------------------------------------------
echo [2/5] Configuration setup...
echo.
echo This script will create a .env file with your settings.
echo You will need:
echo   - Anthropic API key (required)
echo   - Port number (optional, default: 3000)
echo.

REM Check if .env already exists
if exist .env (
    echo [WARNING] .env file already exists.
    set /p overwrite="Overwrite existing .env file? (y/N): "
    if /i not "!overwrite!"=="y" (
        echo.
        echo Setup cancelled. Existing .env file preserved.
        pause
        exit /b 0
    )
)

REM Prompt for Anthropic API key
:ask_api_key
set /p ANTHROPIC_API_KEY="Enter your Anthropic API key: "
if "!ANTHROPIC_API_KEY!"=="" (
    echo [ERROR] API key cannot be empty.
    goto ask_api_key
)

REM Prompt for port (optional)
set /p PORT="Enter port number (press Enter for default 3000): "
if "!PORT!"=="" set PORT=3000

echo.

REM ----------------------------------------------------------------------------
REM Step 3: Create .env File
REM ----------------------------------------------------------------------------
echo [3/5] Creating .env file...

(
echo # Minimal Agent Configuration
echo # Generated by setup.bat on %date% %time%
echo.
echo # Anthropic API Key ^(required^)
echo ANTHROPIC_API_KEY=!ANTHROPIC_API_KEY!
echo.
echo # Server Port ^(default: 3000^)
echo PORT=!PORT!
) > .env

if %errorlevel% neq 0 (
    echo [ERROR] Failed to create .env file.
    pause
    exit /b 1
)

echo [OK] .env file created
echo.

REM ----------------------------------------------------------------------------
REM Step 4: Build Docker Image
REM ----------------------------------------------------------------------------
echo [4/5] Building Docker image...
echo This may take a few minutes on first run...
echo.

docker build -t minimal-agent .
if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Docker build failed.
    pause
    exit /b 1
)

echo.
echo [OK] Docker image built successfully
echo.

REM ----------------------------------------------------------------------------
REM Step 5: Verify Setup
REM ----------------------------------------------------------------------------
echo [5/5] Verifying setup...
echo.

REM Check if .env exists
if not exist .env (
    echo [ERROR] .env file not found
    pause
    exit /b 1
)
echo [OK] .env file exists

REM Check if Docker image exists
docker image inspect minimal-agent >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker image 'minimal-agent' not found
    pause
    exit /b 1
)
echo [OK] Docker image exists
echo.

echo ============================================================================
echo Setup Complete!
echo ============================================================================
echo.
echo Next steps:
echo   1. Start the agent:    start.bat
echo   2. Stop the agent:     stop.bat
echo   3. View logs:          docker logs minimal-agent
echo.
echo The agent will be available at: http://localhost:!PORT!
echo.
pause
