#!/bin/bash
set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Welcome message
echo ""
echo "════════════════════════════════════════"
echo "  Minimal Agent Setup"
echo "════════════════════════════════════════"
echo ""

# Check Docker availability
echo "Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed${NC}"
    echo "Please install Docker Desktop from https://docker.com"
    exit 1
fi

# Verify Docker daemon is running
if ! docker info &> /dev/null; then
    echo -e "${RED}Error: Docker is not running${NC}"
    echo "Please start Docker Desktop and try again"
    exit 1
fi

echo -e "${GREEN}✓ Docker is available${NC}"

# Check for existing .env
if [ -f .env ]; then
    echo ""
    echo -e "${YELLOW}.env already exists${NC}"
    read -p "Reconfigure? (y/n): " reconfigure
    if [ "$reconfigure" != "y" ]; then
        echo "Keeping existing configuration"
        exit 0
    fi
    echo "Reconfiguring..."
fi

# Prompt for API key
echo ""
read -sp "Enter your ANTHROPIC_API_KEY: " api_key
echo ""

# Basic validation (starts with sk-)
if [[ ! $api_key =~ ^sk- ]]; then
    echo -e "${YELLOW}⚠ Warning: API key should start with 'sk-'${NC}"
    read -p "Continue anyway? (y/n): " continue
    if [ "$continue" != "y" ]; then
        echo "Setup cancelled"
        exit 1
    fi
fi

# Optional: Google OAuth
echo ""
read -p "Do you need Google OAuth credentials? (y/n): " needs_google
google_id=""
google_secret=""

if [ "$needs_google" = "y" ]; then
    read -p "GOOGLE_OAUTH_CLIENT_ID: " google_id
    read -sp "GOOGLE_OAUTH_CLIENT_SECRET: " google_secret
    echo ""
fi

# Runtime selection
echo ""
echo "Select runtime agent:"
echo "1) Claude (Recommended)"
echo "2) Codex"
echo "3) Gemini"
read -p "Choice (1-3): " runtime_choice

case $runtime_choice in
    1) runtime="claude" ;;
    2) runtime="codex" ;;
    3) runtime="gemini" ;;
    *)
        echo -e "${YELLOW}Invalid choice. Defaulting to Claude.${NC}"
        runtime="claude"
        ;;
esac

# Generate .env file
cat > .env << EOF
# Generated by setup.sh on $(date)
ANTHROPIC_API_KEY=${api_key}
RUNTIME_AGENT=${runtime}
EOF

if [ "$needs_google" = "y" ]; then
    cat >> .env << EOF
GOOGLE_OAUTH_CLIENT_ID=${google_id}
GOOGLE_OAUTH_CLIENT_SECRET=${google_secret}
EOF
fi

echo -e "${GREEN}✓ Configuration saved to .env${NC}"

# Pull latest runtime image
echo ""
echo "Pulling latest zipsa-runtime image..."
if docker pull ghcr.io/westbrookai/zipsa-runtime:latest; then
    echo -e "${GREEN}✓ Runtime image downloaded${NC}"
else
    echo -e "${YELLOW}⚠ Failed to pull image. Will retry on first start.${NC}"
fi

# Success message
echo ""
echo "════════════════════════════════════════"
echo -e "${GREEN}✓ Setup complete!${NC}"
echo "════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Run './start.sh' to launch the agent"
echo "  2. Wait for initialization to complete"
echo "  3. Start chatting with your agent"
echo ""
