@echo off
setlocal enabledelayedexpansion

echo.
echo ========================================
echo   Minimal Agent Setup
echo ========================================
echo.

REM Check Docker availability
echo Checking Docker installation...
docker --version >nul 2>&1
if errorlevel 1 (
    echo Error: Docker is not installed
    echo Please install Docker Desktop from https://docker.com
    exit /b 1
)

REM Verify Docker daemon is running
docker info >nul 2>&1
if errorlevel 1 (
    echo Error: Docker is not running
    echo Please start Docker Desktop and try again
    exit /b 1
)

echo [OK] Docker is available
echo.

REM Check for existing .env
if exist .env (
    echo .env already exists
    set /p reconfigure="Reconfigure? (y/n): "
    if /i not "!reconfigure!"=="y" (
        echo Keeping existing configuration
        exit /b 0
    )
    echo Reconfiguring...
)

REM Prompt for API key
echo.
set /p api_key="Enter your ANTHROPIC_API_KEY: "

REM Basic validation
echo !api_key! | findstr /r /c:"^sk-" >nul
if errorlevel 1 (
    echo Warning: API key should start with 'sk-'
    set /p continue="Continue anyway? (y/n): "
    if /i not "!continue!"=="y" (
        echo Setup cancelled
        exit /b 1
    )
)

REM Optional: Google OAuth
echo.
set /p needs_google="Do you need Google OAuth credentials? (y/n): "
set google_id=
set google_secret=

if /i "!needs_google!"=="y" (
    set /p google_id="GOOGLE_OAUTH_CLIENT_ID: "
    set /p google_secret="GOOGLE_OAUTH_CLIENT_SECRET: "
)

REM Runtime selection
echo.
echo Select runtime agent:
echo 1^) Claude (Recommended)
echo 2^) Codex
echo 3^) Gemini
set /p runtime_choice="Choice (1-3): "

if "!runtime_choice!"=="1" set runtime=claude
if "!runtime_choice!"=="2" set runtime=codex
if "!runtime_choice!"=="3" set runtime=gemini
if "!runtime!"=="" (
    echo Invalid choice. Defaulting to Claude.
    set runtime=claude
)

REM Generate .env file
(
echo # Generated by setup.bat on %date% %time%
echo ANTHROPIC_API_KEY=!api_key!
echo RUNTIME_AGENT=!runtime!
) > .env

if /i "!needs_google!"=="y" (
    (
    echo GOOGLE_OAUTH_CLIENT_ID=!google_id!
    echo GOOGLE_OAUTH_CLIENT_SECRET=!google_secret!
    ) >> .env
)

echo [OK] Configuration saved to .env

REM Pull latest runtime image
echo.
echo Pulling latest zipsa-runtime image...
docker pull ghcr.io/westbrookai/zipsa-runtime:latest
if errorlevel 1 (
    echo Warning: Failed to pull image. Will retry on first start.
) else (
    echo [OK] Runtime image downloaded
)

REM Success message
echo.
echo ========================================
echo [OK] Setup complete!
echo ========================================
echo.
echo Next steps:
echo   1. Run 'start.bat' to launch the agent
echo   2. Wait for initialization to complete
echo   3. Start chatting with your agent
echo.

endlocal
